WINDOW_WIDTH = 1280
WINDOW_HEGHT = 720

VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144

PLAYER_WALK_SPEED = 60

--SEGA (kerf pick)
-- VIRTUAL_WIDTH = 320
-- VIRTUAL_HEIGHT = 224

--SNES
-- VIRTUAL_WIDTH = 256
-- VIRTUAL_HEIGHT = 224

BABY_BALLOON_OFFSET_X = 15
BABY_BALLOON_OFFSET_Y = 12

BABY_LOLLIPOP_OFFSET_X = 7
BABY_LOLLIPOP_OFFSET_Y = 6

PLAYER_BALLOON_OFFSET_X = 8
PLAYER_BALLOON_OFFSET_Y = 0

PLAYER_LOLLIPOP_OFFSET_X = -8
PLAYER_LOLLIPOP_OFFSET_Y = 0

