WINDOW_WIDTH = 1280
WINDOW_HEGHT = 720

VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144

PLAYER_WALK_SPEED = 60

--SEGA (kerf pick)
-- VIRTUAL_WIDTH = 320
-- VIRTUAL_HEIGHT = 224

--SNES
-- VIRTUAL_WIDTH = 256
-- VIRTUAL_HEIGHT = 224

BABY_BALLOON_OFFSET_X = 15
BABY_BALLOON_OFFSET_Y = -12

BABY_LOLLIPOP_OFFSET_X = 7
BABY_LOLLIPOP_OFFSET_Y = -6

PLAYER_BALLOON_OFFSET_X = 12  
PLAYER_BALLOON_OFFSET_Y = -6 

ROTATED_BALLOON_OFFSET_X = 16 
ROTATED_BALLOON_OFFSET_Y = 34 

PLAYER_LOLLIPOP_OFFSET_X = 5 
PLAYER_LOLLIPOP_OFFSET_Y = 16

BACKGROUND_X_SCROLL_SPEED = 30
BACKGROUND_X_LOOP_POINT = 272

-- BACKGROUND_Y_SCROLL_SPEED = 15
BACKGROUND_Y_LOOP_POINT = 288

MOM_BAG_OFFSET_X = 6
MOM_BAG_OFFSET_Y = 26